services:
  mysql:
    image: 'mysql:8.4'
    environment:
      - 'MYSQL_DATABASE=chat'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=admain'
    ports:
      - '3306:3306'
